---
strategy: polling
no_screen_padding: 'no'
dark_mode: 'no'
static_data: ''
polling_verb: get
polling_url: https://wandmalfarbe.github.io/trmnl-uestra-status-elevators-escalators/result.json
polling_headers: ''
polling_body: 
id: 221170
custom_fields:
- keyname: ignore
  name: About This Plugin
  field_type: author_bio
  description: Show the status of elevators and escalators from the public transport operator ÜSTRA in Hannover.
  github_url: https://github.com/Wandmalfarbe/trmnl-uestra-status-elevators-escalators
name: 'ÜSTRA Status: Aufzüge & Rolltreppen'
refresh_interval: 60 # Minutes
